### ISSUE TITLE
PM Review: Products

### ISSUE THREAD

**Issue by AnnaMKPaschall** [AnnaMKPaschall/emporia#3]
- [x] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + shift + R)
- [x] Logged in user able to add, edit, and delete products associated with their id
- [x] Product index page exists, will be better incorporated with landing page
- [x] Product show page shows delete, update buttons when appropriate
- [x] Redirects from create, update will be to landing page once built
- [x] Additional pending MVPs that impact overall, current design: reviews, cart, categories

**Comment by andrewlangston** [comment]
Hey Anna,

Great work so far on this feature. There are a few CSS styling adjustments to be made, and as you note, some sub-features to be implemented when other features are up and running. Let me know when these are final and we can re-review. Thanks!
